# Generated by Django 5.2.4 on 2025-07-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_category_task_priority_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
